# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-23 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180223_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='label',
        ),
    ]
